Подключение контентной графики
htmlacademy-htmlcss/1772011-sedona-31 pull request #5
Opened 2021-06-18 20:29 UTC by DargoDag

2021-06-22 15:09 UTC, haschish commented
в index.html нет больше контентных изображений?

2021-06-22 15:10 UTC, haschish commented on index.html
> +        <img src="img/logo.png" alt="логотип" width="138" height="70" />
в index.html нет больше контентных изображений?

2021-06-24 17:50 UTC, avylando requested changes
Привет! Нужно поправить:
+ Не подключена большая часть картинок на обеих страницах
+ Неправильный путь к фавиконке
+ Именование файлов - старайся использовать единый стиль разделителей, либо через дефис, либо через нижнее подчеркивание (и конечно требования критерия https://up.htmlacademy.ru/htmlcss/31/criteries#b14)

2021-06-24 17:50 UTC, avylando commented on catalog.html
> +                <img src="img/item1.jpg" alt="Гостиница" width="135" height="90" />
Имена файлов делай понятными, не просто item1,2,3
Они должны быть информативными, чтобы можно было легко ориентироваться в папке с картинками
Например amara-hotel.jpg

2021-06-24 17:50 UTC, avylando commented on index.html
> +        <img src="img/logo.png" alt="логотип" width="138" height="70" />
+1
На главной нужно подключить изображения
Подсказка: карта - это не контентное изображение, его будем подключать через css

2021-06-24 17:50 UTC, avylando commented on catalog.html
>                  <div class="item__descr-title">
На этой странице не все изображения подключены - лого, иконки соцсетей, лого академии

2021-06-24 17:50 UTC, avylando commented on catalog.html
> +    <link rel="icon" type="image/svg+xml" href="/favico.svg" />
Фавиконка не подгрузилась - она лежит в корне, путь должен быть без слэша
И название поправь пожалуйста - favicoN

2021-06-25 22:21 UTC, avylando approved these changes
Задание принимаю, с одним комментом
Поправь это пожалуйста в следующем пуллреквесте

2021-06-25 22:21 UTC, avylando commented on catalog.html
> +        <img src="img/catalog_bcgr.jpg" alt="" />
Это не контентное изображение, а фон
Его будем подключать через css

2021-06-25 22:23 UTC, avylando commented on index.html
> +            <img src="img/city.jpg" alt="настоящик городок" />
Нужно прописать размеры

2021-06-25 22:23 UTC, avylando commented on index.html
> +            <img src="img/bridge.jpg" alt="мост дьявола" />
И здесь

2021-06-25 22:23 UTC, avylando commented on index.html
> +        <img src="img/logo_academy.png" alt="лого академии" />
И здесь везде размеры нужны

2021-06-25 22:23 UTC, merged